name: "Install Rust for Substrate"
description: "Install Rust configured for Substrate"

inputs:
  toolchain_build: # id of input
    description: "Which version of rust toolchain to use"
    required: false
    default: "nightly-2021-03-01"

runs:
  using: "composite"
  steps:
    - name: Get current arch
      shell: bash
      run: |
        uname -m

    - name: Install Dependencies
      shell: bash
      run: >
        sudo apt install -y git clang curl libssl-dev llvm libudev-dev

      # sudo apt install -y build-essential cmake clang curl git libclang-dev libssl-dev libudev-dev llvm pkg-config

    - name: Install Rustup
      shell: bash
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source ~/.cargo/env
        rustup default stable
        rustup update stable
        rustup update ${{ inputs.toolchain_build }}
        rustup target add wasm32-unknown-unknown --toolchain ${{ inputs.toolchain_build }}
