name: "Install Rust for Substrate"
description: "Install Rust configured for Substrate"

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: >
        sudo apt install -y build-essential cmake clang curl git libclang-dev libssl-dev libudev-dev llvm pkg-config

    - name: Install Rustup
      shell: bash
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source ~/.cargo/env
        rustup default stable
        rustup update stable
        rustup update nightly
        rustup target add wasm32-unknown-unknown --toolchain nightly
