version: "3.8"

services:
  opportunity-standalone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opportunity-standalone
    volumes:
      - "data-node:/data"
    ports:
      - "30333:30333"
    command: >-
      --chain opportunity
      --base-path /data
      --port 30333
      --name "${NAME}"
      --validator

volumes:
  data-node:
    name: ${NAME}-name
