name: Build Binaries

permissions:
  contents: read

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-build:
    strategy:
      matrix:
        # macos-11 not yet available, currently is in private preview
        os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout - ${{ matrix.os }}
        uses: actions/checkout@v2

      # use once repository is tagged
      # - uses: actions/install-rust@v1
      - name: Rust Install - ${{ matrix.os }}
        uses: ./.github/actions/install-rust

      - name: Run Build - ${{ matrix.os }}
        run: |
          make build-opportunity-standalone

      - name: Upload Artifacts - ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: binaries-artifact
          path: |
            ./target/release/opportunity-standalone
