name: Docker Build

on:
  push:
    branches: [master]
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # disabled for now
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Docker/Dockerfile
          tags: standard-substrate:latest
          load: true
          build-args: |
            toolchainbuild=nightly-2021-03-01
          # push: ${{ github.event_name != 'pull_request' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
