name: Build Docker

permissions:
  contents: read

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  # will turn on once releases are streamlined
  # release:
  #   types:
  #     - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # disabled for now
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Docker/Dockerfile.release
          tags: standard-substrate:latest
          load: true
          tags: |
            standardprotocol/standalone:latest
            standardprotocol/standalone:${{ github.event.release.tag_name }}
          build-args: |
            TOOLCHAIN_BUILD=nightly-2021-03-01
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          # push: ${{ github.event_name != 'pull_request' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
