name: Build and Publish Docker

on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    strategy:
      matrix:
        platform: [linux/amd64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: binary-build.yml

      - name: Display structure of downloaded files
        run: ls -R

      - name: Artifact move - ${{ matrix.platform }}
        if: ${{ matrix.platform == 'linux/amd64' }}
        run: |
          mv standard-opportunity-linux-x86_64/opportunity-standalone-linux-x86_64 ./opportunity-standalone

      - name: Artifact move - ${{ matrix.platform }}
        if: ${{ matrix.platform == 'darwin/amd64' }}
        run: |
          mv standard-opportunity-darwin-x86_64/opportunity-standalone-darwin-x86_64 ./opportunity-standalone

      - name: Make executable
        run: |
          chmod +x ./opportunity-standalone

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images - ${{ matrix.platform }}
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Docker/Dockerfile.release
          platforms: ${{ matrix.platform }}
          tags: |
            standardprotocol/standard-opportunity:${{ github.event.release.tag_name }}
            standardprotocol/standard-opportunity:latest
          push: true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: standardprotocol/standard-opportunity:latest
          args: --file=./Docker/Dockerfile.release

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
