name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - "release/**"
  pull_request:
    branches:
      - master
      - "release/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Check Code style quickly by running `rustfmt` over all code

  rust-checks:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/install-rust@v1

      # Check Code style quickly by running `rustfmt` over all code
      - name: Add in rustftm component and run fmt
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Check Build
        run: |
          make check
        # SKIP_WASM_BUILD=1 cargo check --release

      - name: Run tests
        run: |
          make test

      # SKIP_WASM_BUILD=1 cargo test --all
      # - name: Check Build for Benchmarking
      #   run: >
      #     pushd node &&
      #     cargo check --features=runtime-benchmarks --release
