name: Publish release

# permissions:
#   contents: write
#   actions: read
#   metadata: read

# Controls when the action will run.
on:
  push:
    tags:
      - "*.*.*"

  # Dependency on previous successful workflow
  # workflow_run:
  #   workflows: ["Build Binaries"]
  #   branches: [master]
  #   type:
  #     - complete
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: binary-build.yml

      - name: Display structure of downloaded files
        run: ls -R

      - name: Build Changelog
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v1.8.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1.8.6
        id: release-step
        with:
          artifacts: "standard-opportunity-*/*"
          body: ${{ steps.build-changelog.outputs.changelog }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Slack Notification
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Details: ${{ steps.release-step.outputs.url }}"
          SLACK_TITLE: "New release in ${{ github.repository }} - ${{ GITHUB_REF:10 }}"
          SLACK_COLOR: "#008000"
          SLACK_CHANNEL: "github-releases"
          SLACK_USERNAME: "release-bot"
