name: Publish release

# permissions:
#   contents: write
#   actions: read
#   metadata: read

# Controls when the action will run.
on:
  push:
    tags:
      - "*.*.*"

jobs:
  on-success:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: binary-build.yml

      - name: Display structure of downloaded files
        run: ls -R

      - name: Build Changelog
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v1.8.3
        with:
          outputFile: "./release-output.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          cat ./release-output.md

      - uses: ncipollo/release-action@v1.8.6
        id: release-step
        with:
          artifacts: "standard-opportunity-*/*"
          allowUpdates: true
          # body: ${{ steps.build-changelog.outputs.changelog }}
          bodyFile: "./release-output.md"
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - name: Slack Notification
        uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Details: ${{ steps.release-step.outputs.html_url }}"
          SLACK_TITLE: "New release in ${{ github.repository }} - ${{ env.RELEASE_VERSION }}"
          SLACK_COLOR: "#008000"
          SLACK_CHANNEL: "github-releases"
          SLACK_USERNAME: "release-bot"
