name: Release binaries and images

permissions:
  contents: write
  actions: read
  metadata: read

# Controls when the action will run.
on:
  # Dependency on previous successful workflows
  workflow_run:
    workflows: ["Build Binaries"]
    branches:
      - master
    types:
      - complete

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-artifact

      - name: Build Changelog
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v1.8.2

      - name: Release
        uses: softprops/action-gh-release@v1
        id: release-step
        if: startsWith(github.ref, 'refs/tags/')
        body: ${{steps.build-changelog.outputs.changelog}}
        with:
          files: |
            opportunity-standalone

      - name: Send off notification - TODO
        run: |
          echo "Release URL: ${{ steps.release-step.outputs.url }}"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send off notification - TODO
        run: |
          echo "Failed"
