name: Release binaries and images

# permissions:
#   contents: write
#   actions: read
#   metadata: read

# Controls when the action will run.
on:
  # Dependency on previous successful workflow
  workflow_run:
    workflows: ["Build Binaries"]
    branches: [master]
    type:
      - complete

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    # env:
    #   GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2

      - name: Download binaries
        uses: actions/download-artifact@v2
        # with:
        #   path: ./bin
        #   name: binaries-*

      - name: Display structure of downloaded files
        run: ls -R
        # working-directory: ./bin

      - name: Build Changelog
        id: build-changelog
        uses: mikepenz/release-changelog-builder-action@v1.8.2

      - uses: ncipollo/release-action@v1.8.6
        id: release-step
        with:
          artifacts: "standard-opportunity-*"
          body: ${{steps.build-changelog.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send off notification - TODO
        run: |
          echo "Release URL: ${{ steps.release-step.outputs.url }}"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Send off notification - TODO
        run: |
          echo "Failed"
